name: Check MDX Links

on:
  push:
    paths:
      - '**/*.mdx'
  pull_request:
    paths:
      - '**/*.mdx'

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - run: yarn check-links